# ACS API Request

In [1]:
# Import libraries
import pandas as pd
import requests
import time

In [2]:
# Geographic codes
relfile = pd.read_csv(r'C:\Users\HerreraMartinezR\OneDrive - NYC Office of Management and Budget\HTM Projects\ACS_Warehouse\docs\tab20_puma520_cousub20_natl.txt', sep = '|', header = 0, dtype = 'str')
relfile.head()

,OID_PUMA5_20,GEOID_PUMA5_20,NAMELSAD_PUMA5_20,AREALAND_PUMA5_20,AREAWATER_PUMA5_20,MTFCC_PUMA5_20,FUNCSTAT_PUMA5_20,OID_COUSUB_20,GEOID_COUSUB_20,NAMELSAD_COUSUB_20,AREALAND_COUSUB_20,AREAWATER_COUSUB_20,MTFCC_COUSUB_20,CLASSFP_COUSUB_20,FUNCSTAT_COUSUB_20,AREALAND_PART,AREAWATER_PART
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,27690590833492,6001037700,Ituau county,12986619,51344770,G4040,T1,A,12986619,51344770
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,27690590833493,6001051300,Ma'oputasi county,17111108,30945042,G4040,T1,A,17111108,30945042
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,27690590833494,6001067300,Sa'ole county,5954576,47875714,G4040,T1,A,5954576,47875714
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,27690590833495,6001072100,Sua county,17200142,63697222,G4040,T1,A,17200142,63697222
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,27690590833496,6001086500,Vaifanua county,11872421,155861930,G4040,T1,A,11872421,155861930

In [3]:
# Extract PUMA codes for NYC
pumas_nyc = relfile.loc[relfile['NAMELSAD_PUMA5_20'].str.contains('NYC') == True, 'GEOID_PUMA5_20'].reset_index(drop = True)
# Drop the state id
pumas_nyc = pumas_nyc.str[2:7].copy()
# Drop missing values
pumas_nyc = pumas_nyc.dropna()
# Drop any duplicates
pumas_nyc = pumas_nyc.drop_duplicates().reset_index(drop = True)
# Check the results
pumas_nyc.head()

0    04103
1    04104
2    04107
3    04108
4    04109
Name: GEOID_PUMA5_20, dtype: object

In [4]:
# API  Key 
with open(r"C:\Users\HerreraMartinezR\OneDrive - NYC Office of Management and Budget\Data\API_Keys\CensusAPIKey.txt", 'r') as file:
   MyKey = file.read().strip()

## DP02

In [5]:
# API Key and URL
api_key = MyKey

# API for ACS 1-year Data Profile Tables
api_url_2024 = 'https://api.census.gov/data/2024/acs/acs1/profile'
api_url_2023 = 'https://api.census.gov/data/2023/acs/acs1/profile'
api_url_2022 = 'https://api.census.gov/data/2022/acs/acs1/profile'
# api_url_2021 = 'https://api.census.gov/data/2021/acs/acs1/profile' # NOTE: Limited number of pumas available
# api_url_2020 = 'https://api.census.gov/data/2020/acs/acs1/profile' # NOTE: Not released due to pandemic

# Tables/variables
variables =  ['group(DP02)']

In [6]:
# Request
   
geo_code =  pumas_nyc.tolist()      
api_list = [api_url_2024, api_url_2023, api_url_2022]
vintages = [2024, 2023, 2022]

dfs_by_vintage = {}

for url, year in zip(api_list, vintages):
    rows = []
    for code in geo_code:
        params = {
            "get": ",".join(variables),
            "for": f"public use microdata area:{code}", 
            "in": "state:36",
            "key": api_key
        }
        try:
            resp = requests.get(url, params=params, timeout=60)
            resp.raise_for_status()
            json_data = resp.json()

            headers = json_data[0]
            for vals in json_data[1:]:
                rec = dict(zip(headers, vals))
                rec["vintage"] = year
                rec['sample'] = url.split("/acs/")[1].split("/")[0]     # TEST: Including ACS sample type in the output (1 year or 5 year)
                rec['group'] = variables[0]                             # TEST: Include the variable group. WILL BE AN ISSUE FOR IND. VAR??
                rows.append(rec)

        except requests.RequestException as e:
            print(f"[{year}] Error fetching puma {code}: {e}")

        time.sleep(0.15)                                            # be nice to the API

    df_year = pd.DataFrame(rows)
    
    # Optional: make numeric columns numeric
    non_numeric = {"place", "state", "county", "GEO_ID" , "NAME", "vintage", "sample", "group"}
    num_cols = [c for c in df_year.columns if c not in non_numeric]
    df_year[num_cols] = df_year[num_cols].apply(pd.to_numeric, errors="coerce")

    dfs_by_vintage[year] = df_year

In [7]:
# Store as df
df_2022 = dfs_by_vintage[2022]
df_2023 = dfs_by_vintage[2023]
df_2024 = dfs_by_vintage[2024]

print('2022 df shape', df_2022.shape)
print('2023 df shape', df_2023.shape)
print('2024 df shape', df_2024.shape)

2022 df shape (55, 1239)
2023 df shape (55, 1239)
2024 df shape (55, 1239)

In [8]:
df_2022

,DP02_0001E,DP02_0001EA,DP02_0001M,DP02_0001MA,DP02_0001PE,DP02_0001PEA,DP02_0001PM,DP02_0001PMA,DP02_0002E,DP02_0002EA,...,DP02_0154PEA,DP02_0154PM,DP02_0154PMA,GEO_ID,NAME,state,public use microdata area,vintage,sample,group
0,73474,NaN,4448,NaN,73474,NaN,-888888888,NaN,15232,NaN,...,NaN,3.3,NaN,795P200US3604103,NYC-Manhattan Community District 3--Lower East...,36,4103,2022,acs1,group(DP02)
1,67653,NaN,4580,NaN,67653,NaN,-888888888,NaN,13438,NaN,...,NaN,3.1,NaN,795P200US3604104,NYC-Manhattan Community District 4--Chelsea & ...,36,4104,2022,acs1,group(DP02)
2,115928,NaN,6894,NaN,115928,NaN,-888888888,NaN,42508,NaN,...,NaN,2.2,NaN,795P200US3604107,NYC-Manhattan Community District 7--Upper West...,36,4107,2022,acs1,group(DP02)
3,114602,NaN,5481,NaN,114602,NaN,-888888888,NaN,41410,NaN,...,NaN,1.4,NaN,795P200US3604108,NYC-Manhattan Community District 8--Upper East...,36,4108,2022,acs1,group(DP02)
4,44758,NaN,3670,NaN,44758,NaN,-888888888,NaN,9119,NaN,...,NaN,4.5,NaN,795P200US3604109,NYC-Manhattan Community District 9--Morningsid...,36,4109,2022,acs1,group(DP02)
5,63590,NaN,4485,NaN,63590,NaN,-888888888,NaN,12530,NaN,...,NaN,3.7,NaN,795P200US3604110,NYC-Manhattan Community District 10--Harlem PU...,36,4110,2022,acs1,group(DP02)
6,57494,NaN,3883,NaN,57494,NaN,-888888888,NaN,11026,NaN,...,NaN,4.1,NaN,795P200US3604111,NYC-Manhattan Community District 11--East Harl...,36,4111,2022,acs1,group(DP02)
7,82694,NaN,4856,NaN,82694,NaN,-888888888,NaN,22416,NaN,...,NaN,2.8,NaN,795P200US3604112,NYC-Manhattan Community District 12--Washingto...,36,4112,2022,acs1,group(DP02)
8,78584,NaN,5257,NaN,78584,NaN,-888888888,NaN,22643,NaN,...,NaN,1.9,NaN,795P200US3604121,NYC-Manhattan Community Districts 1 & 2--Finan...,36,4121,2022,acs1,group(DP02)
9,105067,NaN,6067,NaN,105067,NaN,-888888888,NaN,27453,NaN,...,NaN,1.7,NaN,795P200US3604165,NYC-Manhattan Community Districts 5 & 6--Midto...,36,4165,2022,acs1,group(DP02)
10,52974,NaN,3749,NaN,52974,NaN,-888888888,NaN,11091,NaN,...,NaN,4.3,NaN,795P200US3604204,NYC-Bronx Community District 4--Highbridge & C...,36,4204,2022,acs1,group(DP02)
11,42620,NaN,2930,NaN,42620,NaN,-888888888,NaN,10932,NaN,...,NaN,3.6,NaN,795P200US3604205,NYC-Bronx Community District 5--Morris Heights...,36,4205,2022,acs1,group(DP02)
12,52601,NaN,3395,NaN,52601,NaN,-888888888,NaN,14248,NaN,...,NaN,2.9,NaN,795P200US3604207,"NYC-Bronx Community District 7--Fordham, Bedfo...",36,4207,2022,acs1,group(DP02)
13,38455,NaN,2401,NaN,38455,NaN,-888888888,NaN,11279,NaN,...,NaN,2.3,NaN,795P200US3604208,"NYC-Bronx Community District 8--Riverdale, Kin...",36,4208,2022,acs1,group(DP02)
14,70168,NaN,4327,NaN,70168,NaN,-888888888,NaN,19224,NaN,...,NaN,3.4,NaN,795P200US3604209,NYC-Bronx Community District 9--Soundview & Pa...,36,4209,2022,acs1,group(DP02)
15,56040,NaN,3671,NaN,56040,NaN,-888888888,NaN,18003,NaN,...,NaN,3.0,NaN,795P200US3604210,NYC-Bronx Community District 10--Co-op City & ...,36,4210,2022,acs1,group(DP02)
16,44217,NaN,3000,NaN,44217,NaN,-888888888,NaN,14533,NaN,...,NaN,2.9,NaN,795P200US3604211,NYC-Bronx Community District 11--Pelham Parkwa...,36,4211,2022,acs1,group(DP02)
17,57194,NaN,3834,NaN,57194,NaN,-888888888,NaN,16588,NaN,...,NaN,3.8,NaN,795P200US3604212,"NYC-Bronx Community District 12--Wakefield, Wi...",36,4212,2022,acs1,group(DP02)
18,56269,NaN,3435,NaN,56269,NaN,-888888888,NaN,12878,NaN,...,NaN,4.3,NaN,795P200US3604221,"NYC-Bronx Community Districts 1 & 2--Melrose, ...",36,4221,2022,acs1,group(DP02)
19,62497,NaN,4008,NaN,62497,NaN,-888888888,NaN,11038,NaN,...,NaN,3.8,NaN,795P200US3604263,NYC-Bronx Community Districts 3 & 6--Morrisani...,36,4263,2022,acs1,group(DP02)
20,84718,NaN,4086,NaN,84718,NaN,-888888888,NaN,24370,NaN,...,NaN,2.0,NaN,795P200US3604301,NYC-Brooklyn Community District 1--Williamsbur...,36,4301,2022,acs1,group(DP02)
21,63155,NaN,3675,NaN,63155,NaN,-888888888,NaN,19523,NaN,...,NaN,2.5,NaN,795P200US3604302,NYC-Brooklyn Community District 2--Downtown Br...,36,4302,2022,acs1,group(DP02)
22,69016,NaN,3955,NaN,69016,NaN,-888888888,NaN,15331,NaN,...,NaN,2.6,NaN,795P200US3604303,NYC-Brooklyn Community District 3--Bedford-Stu...,36,4303,2022,acs1,group(DP02)
23,38586,NaN,2760,NaN,38586,NaN,-888888888,NaN,8857,NaN,...,NaN,3.2,NaN,795P200US3604304,NYC-Brooklyn Community District 4--Bushwick PU...,36,4304,2022,acs1,group(DP02)
24,76572,NaN,4185,NaN,76572,NaN,-888888888,NaN,17841,NaN,...,NaN,2.3,NaN,795P200US3604305,NYC-Brooklyn Community District 5--East New Yo...,36,4305,2022,acs1,group(DP02)
25,50621,NaN,3042,NaN,50621,NaN,-888888888,NaN,20132,NaN,...,NaN,1.9,NaN,795P200US3604306,NYC-Brooklyn Community District 6--Park Slope ...,36,4306,2022,acs1,group(DP02)
26,44274,NaN,2148,NaN,44274,NaN,-888888888,NaN,20038,NaN,...,NaN,2.5,NaN,795P200US3604307,NYC-Brooklyn Community District 7--Sunset Park...,36,4307,2022,acs1,group(DP02)
27,48645,NaN,3635,NaN,48645,NaN,-888888888,NaN,13467,NaN,...,NaN,3.7,NaN,795P200US3604308,NYC-Brooklyn Community District 8--Crown Heigh...,36,4308,2022,acs1,group(DP02)
28,39630,NaN,2790,NaN,39630,NaN,-888888888,NaN,10343,NaN,...,NaN,3.1,NaN,795P200US3604309,NYC-Brooklyn Community District 9--Crown Heigh...,36,4309,2022,acs1,group(DP02)
29,47484,NaN,2771,NaN,47484,NaN,-888888888,NaN,21242,NaN,...,NaN,2.2,NaN,795P200US3604310,NYC-Brooklyn Community District 10--Bay Ridge ...,36,4310,2022,acs1,group(DP02)
30,66339,NaN,3996,NaN,66339,NaN,-888888888,NaN,31642,NaN,...,NaN,1.9,NaN,795P200US3604311,NYC-Brooklyn Community District 11--Bensonhurs...,36,4311,2022,acs1,group(DP02)
31,54133,NaN,3508,NaN,54133,NaN,-888888888,NaN,30441,NaN,...,NaN,3.9,NaN,795P200US3604312,NYC-Brooklyn Community District 12--Borough Pa...,36,4312,2022,acs1,group(DP02)
32,50356,NaN,3752,NaN,50356,NaN,-888888888,NaN,18980,NaN,...,NaN,2.7,NaN,795P200US3604313,NYC-Brooklyn Community District 13--Coney Isla...,36,4313,2022,acs1,group(DP02)
33,62940,NaN,3498,NaN,62940,NaN,-888888888,NaN,24053,NaN,...,NaN,2.1,NaN,795P200US3604314,NYC-Brooklyn Community District 14--Flatbush &...,36,4314,2022,acs1,group(DP02)
34,61746,NaN,3283,NaN,61746,NaN,-888888888,NaN,29186,NaN,...,NaN,2.6,NaN,795P200US3604315,NYC-Brooklyn Community District 15--Sheepshead...,36,4315,2022,acs1,group(DP02)
35,37770,NaN,3275,NaN,37770,NaN,-888888888,NaN,9280,NaN,...,NaN,4.9,NaN,795P200US3604316,NYC-Brooklyn Community District 16--Ocean Hill...,36,4316,2022,acs1,group(DP02)
36,61560,NaN,3220,NaN,61560,NaN,-888888888,NaN,18414,NaN,...,NaN,2.7,NaN,795P200US3604317,NYC-Brooklyn Community District 17--East Flatb...,36,4317,2022,acs1,group(DP02)
37,68816,NaN,3218,NaN,68816,NaN,-888888888,NaN,28595,NaN,...,NaN,1.8,NaN,795P200US3604318,NYC-Brooklyn Community District 18--Canarsie &...,36,4318,2022,acs1,group(DP02)
38,80758,NaN,3517,NaN,80758,NaN,-888888888,NaN,26406,NaN,...,NaN,1.9,NaN,795P200US3604401,NYC-Queens Community District 1--Astoria & Que...,36,4401,2022,acs1,group(DP02)
39,55763,NaN,3306,NaN,55763,NaN,-888888888,NaN,19908,NaN,...,NaN,3.0,NaN,795P200US3604402,NYC-Queens Community District 2--Long Island C...,36,4402,2022,acs1,group(DP02)
40,54221,NaN,3524,NaN,54221,NaN,-888888888,NaN,22535,NaN,...,NaN,2.5,NaN,795P200US3604403,NYC-Queens Community District 3--Jackson Heigh...,36,4403,2022,acs1,group(DP02)
41,53550,NaN,3131,NaN,53550,NaN,-888888888,NaN,21802,NaN,...,NaN,3.7,NaN,795P200US3604404,NYC-Queens Community District 4--Elmhurst & Co...,36,4404,2022,acs1,group(DP02)
42,65971,NaN,3233,NaN,65971,NaN,-888888888,NaN,28824,NaN,...,NaN,1.8,NaN,795P200US3604405,"NYC-Queens Community District 5--Ridgewood, Ma...",36,4405,2022,acs1,group(DP02)
43,56010,NaN,3755,NaN,56010,NaN,-888888888,NaN,23760,NaN,...,NaN,1.6,NaN,795P200US3604406,NYC-Queens Community District 6--Forest Hills ...,36,4406,2022,acs1,group(DP02)
44,96922,NaN,4107,NaN,96922,NaN,-888888888,NaN,47730,NaN,...,NaN,1.8,NaN,795P200US3604407,"NYC-Queens Community District 7--Flushing, Mur...",36,4407,2022,acs1,group(DP02)
45,55342,NaN,3216,NaN,55342,NaN,-888888888,NaN,24108,NaN,...,NaN,1.7,NaN,795P200US3604408,NYC-Queens Community District 8--Fresh Meadows...,36,4408,2022,acs1,group(DP02)
46,44887,NaN,2520,NaN,44887,NaN,-888888888,NaN,21997,NaN,...,NaN,1.8,NaN,795P200US3604409,"NYC-Queens Community District 9--Kew Gardens, ...",36,4409,2022,acs1,group(DP02)
47,39767,NaN,2549,NaN,39767,NaN,-888888888,NaN,20516,NaN,...,NaN,1.6,NaN,795P200US3604410,NYC-Queens Community District 10--South Ozone ...,36,4410,2022,acs1,group(DP02)
48,44752,NaN,2834,NaN,44752,NaN,-888888888,NaN,23579,NaN,...,NaN,2.1,NaN,795P200US3604411,"NYC-Queens Community District 11--Auburndale, ...",36,4411,2022,acs1,group(DP02)
49,82213,NaN,4323,NaN,82213,NaN,-888888888,NaN,32840,NaN,...,NaN,1.8,NaN,795P200US3604412,"NYC-Queens Community District 12--Jamaica, St....",36,4412,2022,acs1,group(DP02)
50,63798,NaN,3457,NaN,63798,NaN,-888888888,NaN,31503,NaN,...,NaN,1.4,NaN,795P200US3604413,NYC-Queens Community District 13--Queens Villa...,36,4413,2022,acs1,group(DP02)
51,45899,NaN,3447,NaN,45899,NaN,-888888888,NaN,18977,NaN,...,NaN,2.2,NaN,795P200US3604414,NYC-Queens Community District 14--The Rockaway...,36,4414,2022,acs1,group(DP02)
52,65022,NaN,3339,NaN,65022,NaN,-888888888,NaN,28677,NaN,...,NaN,2.2,NaN,795P200US3604501,NYC-Staten Island Community District 1--North ...,36,4501,2022,acs1,group(DP02)
53,49768,NaN,3124,NaN,49768,NaN,-888888888,NaN,26601,NaN,...,NaN,2.7,NaN,795P200US3604502,NYC-Staten Island Community District 2--Mid-Is...,36,4502,2022,acs1,group(DP02)
54,55156,NaN,2794,NaN,55156,NaN,-888888888,NaN,36340,NaN,...,NaN,2.3,NaN,795P200US3604503,NYC-Staten Island Community District 3--South ...,36,4503,2022,acs1,group(DP02)

In [9]:
# Save
df_2022.to_csv(r"C:\Users\HerreraMartinezR\OneDrive - NYC Office of Management and Budget\Data\ACS\1_yr_sample\2022\PUMA\1_yr_ACS_2022_PUMA_NYC_DP02.csv", index = False)
df_2023.to_csv(r"C:\Users\HerreraMartinezR\OneDrive - NYC Office of Management and Budget\Data\ACS\1_yr_sample\2023\PUMA\1_yr_ACS_2023_PUMA_NYC_DP02.csv", index = False)
df_2024.to_csv(r"C:\Users\HerreraMartinezR\OneDrive - NYC Office of Management and Budget\Data\ACS\1_yr_sample\2024\PUMA\1_yr_ACS_2024_PUMA_NYC_DP02.csv", index = False)

## DP03

In [10]:
# API Key and URL
api_key = MyKey

# API for ACS 1-year Data Profile Tables
api_url_2024 = 'https://api.census.gov/data/2024/acs/acs1/profile'
api_url_2023 = 'https://api.census.gov/data/2023/acs/acs1/profile'
api_url_2022 = 'https://api.census.gov/data/2022/acs/acs1/profile'
# api_url_2021 = 'https://api.census.gov/data/2021/acs/acs1/profile' # NOTE: Limited number of pumas available
# api_url_2020 = 'https://api.census.gov/data/2020/acs/acs1/profile' # NOTE: Not released due to pandemic

# Tables/variables
variables =  ['group(DP03)']

In [ ]:
# Request
   
geo_code =  pumas_nyc.tolist()      
api_list = [api_url_2024, api_url_2023, api_url_2022]
vintages = [2024, 2023, 2022]
# geo_code = ['04313', '04316', '04317']      # For tests
# api_list = [api_url_2024]                   # For tests
# vintages = [2024]                           # For tests

dfs_by_vintage = {}

for url, year in zip(api_list, vintages):
    rows = []
    for code in geo_code:
        params = {
            "get": ",".join(variables),
            "for": f"public use microdata area:{code}", 
            "in": "state:36",
            "key": api_key
        }
        try:
            resp = requests.get(url, params=params, timeout=90)
            resp.raise_for_status()
            json_data = resp.json()

            headers = json_data[0]
            for vals in json_data[1:]:
                rec = dict(zip(headers, vals))
                rec["vintage"] = year
                rec['sample'] = url.split("/acs/")[1].split("/")[0]     # TEST: Including ACS sample type in the output (1 year or 5 year)
                rec['group'] = variables[0]                             # TEST: Include the variable group. WILL BE AN ISSUE FOR IND. VAR??                
                rows.append(rec)

        except requests.RequestException as e:
            print(f"[{year}] Error fetching puma {code}: {e}")

        time.sleep(0.15)                                            # be nice to the API

    df_year = pd.DataFrame(rows)
    
    # Optional: make numeric columns numeric
    non_numeric = {"place", "state", "county", "GEO_ID" , "NAME", "vintage", "sample", "group"}
    num_cols = [c for c in df_year.columns if c not in non_numeric]
    df_year[num_cols] = df_year[num_cols].apply(pd.to_numeric, errors="coerce")

    dfs_by_vintage[year] = df_year

In [12]:
# Store as df
df_2022 = dfs_by_vintage[2022]
df_2023 = dfs_by_vintage[2023]
df_2024 = dfs_by_vintage[2024]

print('2022 df shape', df_2022.shape)
print('2023 df shape', df_2023.shape)
print('2024 df shape', df_2024.shape)

2022 df shape (55, 1103)
2023 df shape (55, 1103)
2024 df shape (55, 1103)

In [13]:
# Save
df_2022.to_csv(r"C:\Users\HerreraMartinezR\OneDrive - NYC Office of Management and Budget\Data\ACS\1_yr_sample\2022\PUMA\1_yr_ACS_2022_PUMA_NYC_DP03.csv", index = False)
df_2023.to_csv(r"C:\Users\HerreraMartinezR\OneDrive - NYC Office of Management and Budget\Data\ACS\1_yr_sample\2023\PUMA\1_yr_ACS_2023_PUMA_NYC_DP03.csv", index = False)
df_2024.to_csv(r"C:\Users\HerreraMartinezR\OneDrive - NYC Office of Management and Budget\Data\ACS\1_yr_sample\2024\PUMA\1_yr_ACS_2024_PUMA_NYC_DP03.csv", index = False)

## DP04

In [15]:
# API Key and URL
api_key = MyKey

# API for ACS 1-year Data Profile Tables
api_url_2024 = 'https://api.census.gov/data/2024/acs/acs1/profile'
api_url_2023 = 'https://api.census.gov/data/2023/acs/acs1/profile'
api_url_2022 = 'https://api.census.gov/data/2022/acs/acs1/profile'
# api_url_2021 = 'https://api.census.gov/data/2021/acs/acs1/profile' # NOTE: Limited number of pumas available
# api_url_2020 = 'https://api.census.gov/data/2020/acs/acs1/profile' # NOTE: Not released due to pandemic

# Tables/variables
variables =  ['group(DP04)']

In [16]:
# Request
   
geo_code =  pumas_nyc.tolist()      
api_list = [api_url_2024, api_url_2023, api_url_2022]
vintages = [2024, 2023, 2022]
# geo_code = ['04313', '04316', '04317']      # For tests
# api_list = [api_url_2024]                   # For tests
# vintages = [2024]                           # For tests

dfs_by_vintage = {}

for url, year in zip(api_list, vintages):
    rows = []
    for code in geo_code:
        params = {
            "get": ",".join(variables),
            "for": f"public use microdata area:{code}", 
            "in": "state:36",
            "key": api_key
        }
        try:
            resp = requests.get(url, params=params, timeout=90)
            resp.raise_for_status()
            json_data = resp.json()

            headers = json_data[0]
            for vals in json_data[1:]:
                rec = dict(zip(headers, vals))
                rec["vintage"] = year
                rec['sample'] = url.split("/acs/")[1].split("/")[0]     # TEST: Including ACS sample type in the output (1 year or 5 year)
                rec['group'] = variables[0]                             # TEST: Include the variable group. WILL BE AN ISSUE FOR IND. VAR??
                rows.append(rec)

        except requests.RequestException as e:
            print(f"[{year}] Error fetching puma {code}: {e}")

        time.sleep(0.15)                                            # be nice to the API

    df_year = pd.DataFrame(rows)
    
    # Optional: make numeric columns numeric
    non_numeric = {"place", "state", "county", "GEO_ID" , "NAME", "vintage", "sample", "group"}
    num_cols = [c for c in df_year.columns if c not in non_numeric]
    df_year[num_cols] = df_year[num_cols].apply(pd.to_numeric, errors="coerce")

    dfs_by_vintage[year] = df_year

In [17]:
# Store as df
df_2022 = dfs_by_vintage[2022]
df_2023 = dfs_by_vintage[2023]
df_2024 = dfs_by_vintage[2024]

print('2022 df shape', df_2022.shape)
print('2023 df shape', df_2023.shape)
print('2024 df shape', df_2024.shape)

2022 df shape (55, 1151)
2023 df shape (55, 1151)
2024 df shape (55, 1151)

In [18]:
# Save
df_2022.to_csv(r"C:\Users\HerreraMartinezR\OneDrive - NYC Office of Management and Budget\Data\ACS\1_yr_sample\2022\PUMA\1_yr_ACS_2022_PUMA_NYC_DP04.csv", index = False)
df_2023.to_csv(r"C:\Users\HerreraMartinezR\OneDrive - NYC Office of Management and Budget\Data\ACS\1_yr_sample\2023\PUMA\1_yr_ACS_2023_PUMA_NYC_DP04.csv", index = False)
df_2024.to_csv(r"C:\Users\HerreraMartinezR\OneDrive - NYC Office of Management and Budget\Data\ACS\1_yr_sample\2024\PUMA\1_yr_ACS_2024_PUMA_NYC_DP04.csv", index = False)

## DP05

In [19]:
# API Key and URL
api_key = MyKey

# API for ACS 1-year Data Profile Tables
api_url_2024 = 'https://api.census.gov/data/2024/acs/acs1/profile'
api_url_2023 = 'https://api.census.gov/data/2023/acs/acs1/profile'
api_url_2022 = 'https://api.census.gov/data/2022/acs/acs1/profile'
# api_url_2021 = 'https://api.census.gov/data/2021/acs/acs1/profile' # NOTE: Limited number of pumas available
# api_url_2020 = 'https://api.census.gov/data/2020/acs/acs1/profile' # NOTE: Not released due to pandemic

# Tables/variables
variables =  ['group(DP05)']

In [20]:
# Request
   
geo_code =  pumas_nyc.tolist()      
api_list = [api_url_2024, api_url_2023, api_url_2022]
vintages = [2024, 2023, 2022]
# geo_code = ['04313', '04316', '04317']      # For tests
# api_list = [api_url_2024]                   # For tests
# vintages = [2024]                           # For tests

dfs_by_vintage = {}

for url, year in zip(api_list, vintages):
    rows = []
    for code in geo_code:
        params = {
            "get": ",".join(variables),
            "for": f"public use microdata area:{code}", 
            "in": "state:36",
            "key": api_key
        }
        try:
            resp = requests.get(url, params=params, timeout=90)
            resp.raise_for_status()
            json_data = resp.json()

            headers = json_data[0]
            for vals in json_data[1:]:
                rec = dict(zip(headers, vals))
                rec["vintage"] = year
                rec['sample'] = url.split("/acs/")[1].split("/")[0]     # TEST: Including ACS sample type in the output (1 year or 5 year)
                rec['group'] = variables[0]                             # TEST: Include the variable group. WILL BE AN ISSUE FOR IND. VAR??
                rows.append(rec)

        except requests.RequestException as e:
            print(f"[{year}] Error fetching puma {code}: {e}")

        time.sleep(0.15)                                            # be nice to the API

    df_year = pd.DataFrame(rows)
    
    # Optional: make numeric columns numeric
    non_numeric = {"place", "state", "county", "GEO_ID" , "NAME", "vintage", "sample", "group"}
    num_cols = [c for c in df_year.columns if c not in non_numeric]
    df_year[num_cols] = df_year[num_cols].apply(pd.to_numeric, errors="coerce")

    dfs_by_vintage[year] = df_year

In [21]:
# Store as df
df_2022 = dfs_by_vintage[2022]
df_2023 = dfs_by_vintage[2023]
df_2024 = dfs_by_vintage[2024]

print('2022 df shape', df_2022.shape)
print('2023 df shape', df_2023.shape)
print('2024 df shape', df_2024.shape)

2022 df shape (55, 735)
2023 df shape (55, 759)
2024 df shape (55, 871)

In [22]:
# Save
df_2022.to_csv(r"C:\Users\HerreraMartinezR\OneDrive - NYC Office of Management and Budget\Data\ACS\1_yr_sample\2022\PUMA\1_yr_ACS_2022_PUMA_NYC_DP05.csv", index = False)
df_2023.to_csv(r"C:\Users\HerreraMartinezR\OneDrive - NYC Office of Management and Budget\Data\ACS\1_yr_sample\2023\PUMA\1_yr_ACS_2023_PUMA_NYC_DP05.csv", index = False)
df_2024.to_csv(r"C:\Users\HerreraMartinezR\OneDrive - NYC Office of Management and Budget\Data\ACS\1_yr_sample\2024\PUMA\1_yr_ACS_2024_PUMA_NYC_DP05.csv", index = False)