# Format

In [73]:
import numpy as np
import os
import json
import pandas as pd

In [74]:
# DP3, 2024 data
data_df = pd.read_csv(r"C:\Users\HerreraMartinezR\OneDrive - NYC Office of Management and Budget\Data\ACS\1_yr_sample\2024\PUMA\1_yr_ACS_2024_PUMA_NYC_DP03.csv")
data_df

,DP03_0001E,DP03_0001EA,DP03_0001M,DP03_0001MA,DP03_0001PE,DP03_0001PEA,DP03_0001PM,DP03_0001PMA,DP03_0002E,DP03_0002EA,...,DP03_0137MA,DP03_0137PE,DP03_0137PEA,DP03_0137PM,DP03_0137PMA,GEO_ID,NAME,state,public use microdata area,vintage
0,144345,NaN,9269,NaN,144345,NaN,-888888888,NaN,84740,NaN,...,NaN,31.7,NaN,5.0,NaN,NaN,NYC-Manhattan Community District 3--Lower East...,36,4103,2024
1,115236,NaN,9901,NaN,115236,NaN,-888888888,NaN,88148,NaN,...,NaN,15.5,NaN,2.9,NaN,NaN,NYC-Manhattan Community District 4--Chelsea & ...,36,4104,2024
2,202107,NaN,12109,NaN,202107,NaN,-888888888,NaN,134341,NaN,...,NaN,17.9,NaN,3.4,NaN,NaN,NYC-Manhattan Community District 7--Upper West...,36,4107,2024
3,193797,NaN,10319,NaN,193797,NaN,-888888888,NaN,137634,NaN,...,NaN,11.3,NaN,2.4,NaN,NaN,NYC-Manhattan Community District 8--Upper East...,36,4108,2024
4,102122,NaN,8252,NaN,102122,NaN,-888888888,NaN,62957,NaN,...,NaN,33.8,NaN,7.5,NaN,NaN,NYC-Manhattan Community District 9--Morningsid...,36,4109,2024
5,105499,NaN,10057,NaN,105499,NaN,-888888888,NaN,69618,NaN,...,NaN,31.1,NaN,5.4,NaN,NaN,NYC-Manhattan Community District 10--Harlem PU...,36,4110,2024
6,111508,NaN,10100,NaN,111508,NaN,-888888888,NaN,63372,NaN,...,NaN,42.6,NaN,5.1,NaN,NaN,NYC-Manhattan Community District 11--East Harl...,36,4111,2024
7,155889,NaN,10361,NaN,155889,NaN,-888888888,NaN,98623,NaN,...,NaN,27.8,NaN,4.6,NaN,NaN,NYC-Manhattan Community District 12--Washingto...,36,4112,2024
8,142503,NaN,10560,NaN,142503,NaN,-888888888,NaN,108486,NaN,...,NaN,9.3,NaN,2.7,NaN,NaN,NYC-Manhattan Community Districts 1 & 2--Finan...,36,4121,2024
9,191133,NaN,12244,NaN,191133,NaN,-888888888,NaN,143202,NaN,...,NaN,14.8,NaN,3.1,NaN,NaN,NYC-Manhattan Community Districts 5 & 6--Midto...,36,4165,2024
10,109381,NaN,7364,NaN,109381,NaN,-888888888,NaN,69838,NaN,...,NaN,48.0,NaN,6.6,NaN,NaN,NYC-Bronx Community District 4--Highbridge & C...,36,4204,2024
11,97401,NaN,7739,NaN,97401,NaN,-888888888,NaN,56443,NaN,...,NaN,53.6,NaN,6.0,NaN,NaN,NYC-Bronx Community District 5--Morris Heights...,36,4205,2024
12,100206,NaN,8787,NaN,100206,NaN,-888888888,NaN,61472,NaN,...,NaN,43.1,NaN,6.3,NaN,NaN,"NYC-Bronx Community District 7--Fordham, Bedfo...",36,4207,2024
13,79552,NaN,6123,NaN,79552,NaN,-888888888,NaN,48439,NaN,...,NaN,28.6,NaN,7.3,NaN,NaN,"NYC-Bronx Community District 8--Riverdale, Kin...",36,4208,2024
14,131309,NaN,10277,NaN,131309,NaN,-888888888,NaN,77757,NaN,...,NaN,36.1,NaN,6.2,NaN,NaN,NYC-Bronx Community District 9--Soundview & Pa...,36,4209,2024
15,109261,NaN,7596,NaN,109261,NaN,-888888888,NaN,63693,NaN,...,NaN,30.5,NaN,5.7,NaN,NaN,NYC-Bronx Community District 10--Co-op City & ...,36,4210,2024
16,95208,NaN,6851,NaN,95208,NaN,-888888888,NaN,59950,NaN,...,NaN,29.0,NaN,5.0,NaN,NaN,NYC-Bronx Community District 11--Pelham Parkwa...,36,4211,2024
17,126536,NaN,8355,NaN,126536,NaN,-888888888,NaN,74028,NaN,...,NaN,35.9,NaN,6.1,NaN,NaN,"NYC-Bronx Community District 12--Wakefield, Wi...",36,4212,2024
18,107287,NaN,7892,NaN,107287,NaN,-888888888,NaN,56220,NaN,...,NaN,53.8,NaN,5.6,NaN,NaN,"NYC-Bronx Community Districts 1 & 2--Melrose, ...",36,4221,2024
19,137783,NaN,9779,NaN,137783,NaN,-888888888,NaN,74528,NaN,...,NaN,57.8,NaN,6.3,NaN,NaN,NYC-Bronx Community Districts 3 & 6--Morrisani...,36,4263,2024
20,167321,NaN,10619,NaN,167321,NaN,-888888888,NaN,123623,NaN,...,NaN,17.5,NaN,3.2,NaN,NaN,NYC-Brooklyn Community District 1--Williamsbur...,36,4301,2024
21,114383,NaN,7391,NaN,114383,NaN,-888888888,NaN,84542,NaN,...,NaN,14.6,NaN,3.2,NaN,NaN,NYC-Brooklyn Community District 2--Downtown Br...,36,4302,2024
22,148980,NaN,10740,NaN,148980,NaN,-888888888,NaN,105593,NaN,...,NaN,26.2,NaN,3.4,NaN,NaN,NYC-Brooklyn Community District 3--Bedford-Stu...,36,4303,2024
23,96401,NaN,7774,NaN,96401,NaN,-888888888,NaN,73681,NaN,...,NaN,21.2,NaN,3.6,NaN,NaN,NYC-Brooklyn Community District 4--Bushwick PU...,36,4304,2024
24,158471,NaN,11166,NaN,158471,NaN,-888888888,NaN,87453,NaN,...,NaN,38.6,NaN,5.3,NaN,NaN,NYC-Brooklyn Community District 5--East New Yo...,36,4305,2024
25,109687,NaN,8987,NaN,109687,NaN,-888888888,NaN,83371,NaN,...,NaN,14.6,NaN,3.3,NaN,NaN,NYC-Brooklyn Community District 6--Park Slope ...,36,4306,2024
26,91698,NaN,7200,NaN,91698,NaN,-888888888,NaN,60743,NaN,...,NaN,29.0,NaN,4.9,NaN,NaN,NYC-Brooklyn Community District 7--Sunset Park...,36,4307,2024
27,100903,NaN,8930,NaN,100903,NaN,-888888888,NaN,74629,NaN,...,NaN,22.2,NaN,4.4,NaN,NaN,NYC-Brooklyn Community District 8--Crown Heigh...,36,4308,2024
28,78804,NaN,8289,NaN,78804,NaN,-888888888,NaN,51897,NaN,...,NaN,25.3,NaN,5.1,NaN,NaN,NYC-Brooklyn Community District 9--Crown Heigh...,36,4309,2024
29,104210,NaN,7417,NaN,104210,NaN,-888888888,NaN,65445,NaN,...,NaN,27.7,NaN,5.3,NaN,NaN,NYC-Brooklyn Community District 10--Bay Ridge ...,36,4310,2024
30,152295,NaN,9826,NaN,152295,NaN,-888888888,NaN,94365,NaN,...,NaN,28.4,NaN,5.6,NaN,NaN,NYC-Brooklyn Community District 11--Bensonhurs...,36,4311,2024
31,142203,NaN,9350,NaN,142203,NaN,-888888888,NaN,84324,NaN,...,NaN,34.5,NaN,6.4,NaN,NaN,NYC-Brooklyn Community District 12--Borough Pa...,36,4312,2024
32,96805,NaN,8644,NaN,96805,NaN,-888888888,NaN,47552,NaN,...,NaN,35.1,NaN,6.0,NaN,NaN,NYC-Brooklyn Community District 13--Coney Isla...,36,4313,2024
33,120012,NaN,7494,NaN,120012,NaN,-888888888,NaN,81077,NaN,...,NaN,25.8,NaN,5.1,NaN,NaN,NYC-Brooklyn Community District 14--Flatbush &...,36,4314,2024
34,116919,NaN,7356,NaN,116919,NaN,-888888888,NaN,63055,NaN,...,NaN,22.6,NaN,4.4,NaN,NaN,NYC-Brooklyn Community District 15--Sheepshead...,36,4315,2024
35,89170,NaN,9049,NaN,89170,NaN,-888888888,NaN,52158,NaN,...,NaN,46.7,NaN,6.0,NaN,NaN,NYC-Brooklyn Community District 16--Ocean Hill...,36,4316,2024
36,109405,NaN,7689,NaN,109405,NaN,-888888888,NaN,70977,NaN,...,NaN,27.3,NaN,5.6,NaN,NaN,NYC-Brooklyn Community District 17--East Flatb...,36,4317,2024
37,117629,NaN,7726,NaN,117629,NaN,-888888888,NaN,70003,NaN,...,NaN,25.5,NaN,4.8,NaN,NaN,NYC-Brooklyn Community District 18--Canarsie &...,36,4318,2024
38,166188,NaN,9392,NaN,166188,NaN,-888888888,NaN,118114,NaN,...,NaN,19.3,NaN,2.9,NaN,NaN,NYC-Queens Community District 1--Astoria & Que...,36,4401,2024
39,116018,NaN,8386,NaN,116018,NaN,-888888888,NaN,82762,NaN,...,NaN,19.5,NaN,3.8,NaN,NaN,NYC-Queens Community District 2--Long Island C...,36,4402,2024
40,131967,NaN,8901,NaN,131967,NaN,-888888888,NaN,87172,NaN,...,NaN,27.8,NaN,4.1,NaN,NaN,NYC-Queens Community District 3--Jackson Heigh...,36,4403,2024
41,134588,NaN,11169,NaN,134588,NaN,-888888888,NaN,83364,NaN,...,NaN,30.7,NaN,4.9,NaN,NaN,NYC-Queens Community District 4--Elmhurst & Co...,36,4404,2024
42,144624,NaN,8990,NaN,144624,NaN,-888888888,NaN,94123,NaN,...,NaN,22.5,NaN,4.9,NaN,NaN,"NYC-Queens Community District 5--Ridgewood, Ma...",36,4405,2024
43,101702,NaN,7707,NaN,101702,NaN,-888888888,NaN,62863,NaN,...,NaN,16.3,NaN,4.8,NaN,NaN,NYC-Queens Community District 6--Forest Hills ...,36,4406,2024
44,217979,NaN,12315,NaN,217979,NaN,-888888888,NaN,130419,NaN,...,NaN,29.8,NaN,4.7,NaN,NaN,"NYC-Queens Community District 7--Flushing, Mur...",36,4407,2024
45,120323,NaN,9089,NaN,120323,NaN,-888888888,NaN,70635,NaN,...,NaN,27.4,NaN,8.1,NaN,NaN,NYC-Queens Community District 8--Fresh Meadows...,36,4408,2024
46,107852,NaN,8824,NaN,107852,NaN,-888888888,NaN,65773,NaN,...,NaN,26.8,NaN,5.3,NaN,NaN,"NYC-Queens Community District 9--Kew Gardens, ...",36,4409,2024
47,104741,NaN,10401,NaN,104741,NaN,-888888888,NaN,59978,NaN,...,NaN,33.6,NaN,6.0,NaN,NaN,NYC-Queens Community District 10--South Ozone ...,36,4410,2024
48,99408,NaN,7828,NaN,99408,NaN,-888888888,NaN,60200,NaN,...,NaN,17.3,NaN,5.0,NaN,NaN,"NYC-Queens Community District 11--Auburndale, ...",36,4411,2024
49,210829,NaN,10538,NaN,210829,NaN,-888888888,NaN,132187,NaN,...,NaN,35.3,NaN,4.8,NaN,NaN,"NYC-Queens Community District 12--Jamaica, St....",36,4412,2024
50,165536,NaN,8726,NaN,165536,NaN,-888888888,NaN,103018,NaN,...,NaN,24.0,NaN,4.1,NaN,NaN,NYC-Queens Community District 13--Queens Villa...,36,4413,2024
51,104770,NaN,8237,NaN,104770,NaN,-888888888,NaN,59117,NaN,...,NaN,37.6,NaN,6.5,NaN,NaN,NYC-Queens Community District 14--The Rockaway...,36,4414,2024
52,152902,NaN,7711,NaN,152902,NaN,-888888888,NaN,91362,NaN,...,NaN,32.3,NaN,5.1,NaN,NaN,NYC-Staten Island Community District 1--North ...,36,4501,2024
53,115611,NaN,7868,NaN,115611,NaN,-888888888,NaN,68769,NaN,...,NaN,28.6,NaN,7.1,NaN,NaN,NYC-Staten Island Community District 2--Mid-Is...,36,4502,2024
54,138293,NaN,9496,NaN,138293,NaN,-888888888,NaN,88797,NaN,...,NaN,19.0,NaN,6.4,NaN,NaN,NYC-Staten Island Community District 3--South ...,36,4503,2024

In [75]:
# labels
with open(r"C:\Users\HerreraMartinezR\OneDrive - NYC Office of Management and Budget\HTM Projects\ACS_Warehouse\docs\dp_variables_2024.json", 'r') as f:
    data = json.load(f)

meta_df = (
    pd.DataFrame.from_dict(data["variables"], orient="index")
      .reset_index()
      .rename(columns={"index": "variable"})
)
meta_df

,variable,label,concept,predicateType,group,limit,predicateOnly,hasGeoCollectionSupport,attributes,required
0,for,Census API FIPS 'for' clause,Census API Geography Specification,fips-for,N/A,0,True,NaN,NaN,NaN
1,in,Census API FIPS 'in' clause,Census API Geography Specification,fips-in,N/A,0,True,NaN,NaN,NaN
2,ucgid,Uniform Census Geography Identifier clause,Census API Geography Specification,ucgid,N/A,0,True,True,NaN,NaN
3,DP02_0126E,Estimate!!ANCESTRY!!Total population!!Arab,Selected Social Characteristics in the United ...,int,DP02,0,NaN,NaN,"DP02_0126EA,DP02_0126M,DP02_0126MA",NaN
4,DP05_0050PE,Percent!!RACE!!Total population!!One race!!Bla...,ACS Demographic and Housing Estimates,float,DP05,0,NaN,NaN,"DP05_0050PEA,DP05_0050PM,DP05_0050PMA",NaN
...,...,...,...,...,...,...,...,...,...,...
1412,DP03_0039PE,Percent!!INDUSTRY!!Civilian employed populatio...,Selected Economic Characteristics,float,DP03,0,NaN,NaN,"DP03_0039PEA,DP03_0039PM,DP03_0039PMA",NaN
1413,DP02_0098E,Estimate!!YEAR OF ENTRY!!Population born outsi...,Selected Social Characteristics in the United ...,int,DP02,0,NaN,NaN,"DP02_0098EA,DP02_0098M,DP02_0098MA",NaN
1414,DP04_0095PE,Percent!!SELECTED MONTHLY OWNER COSTS (SMOC)!!...,Selected Housing Characteristics,float,DP04,0,NaN,NaN,"DP04_0095PEA,DP04_0095PM,DP04_0095PMA",NaN
1415,DP02_0036PE,Percent!!MARITAL STATUS!!Females 15 years and ...,Selected Social Characteristics in the United ...,float,DP02,0,NaN,NaN,"DP02_0036PEA,DP02_0036PM,DP02_0036PMA",NaN
1416,DP05_0098PE,Percent!!HISPANIC OR LATINO AND RACE!!Total po...,ACS Demographic and Housing Estimates,float,DP05,0,NaN,NaN,"DP05_0098PEA,DP05_0098PM,DP05_0098PMA",NaN

In [ ]:
# Extract parameters for function and file name
sample = '1_yr' # or 5_yr
vintage = '2024'
geography = 'PUMA'

In [77]:
# Define Function to format tables
def acs_dp_to_wide(data_df:pd.DataFrame, meta_df:pd.DataFrame, sample:str, vintage:int) -> tuple:
    """
    Function is designed to work with data profile coming from census API requests
    
    Args:
        df_api: Data Profile DataFrame 
        df_meta: Metadata DataFrame
        sample: 1_yr or 5_yr
        vintage: survey year (or last year in 5_yr samples)
    
    Returns:
        pd.DataFrame: Wide format table (variables in rows, geographies in columns) with data profile data

    """
    # PREPARE DATA
    # Remove unnecessary columns from data df
    var_df = data_df.loc[:, ~data_df.columns.str.endswith(('EA', 'MA', 'PEA'))].copy()      # drop annotation columns
    var_df = var_df.drop(columns = ['GEO_ID', 'state', 'vintage', 'NAME'])                  # drop geo_id column (it's empty), state (non-necessary), vintage (useful but makes transpose more difficult),NAME (useful, but messes up the column type)
    
    # Recode missing values
    var_df = var_df.replace([-888888888, -999999999], np.nan)
    
    # Transpose dataframe
    wide_df = var_df.transpose()
    headers = wide_df.iloc[-1].astype(int)                                          # type int to remove decimal point
    wide_df.columns = headers
    wide_df = wide_df[:-1].copy()                                                   # Remove row with headers
    wide_df = wide_df.add_prefix('puma_')
    wide_df = wide_df.reset_index().rename(columns={'index': 'variable'})           # reset index

    # Reincorporate vintage
    wide_df['vintage'] = vintage

    # Add sample indicator
    wide_df['sample'] = sample
    
    # Get variable base name
    wide_df['var_name_base'] = wide_df['variable'].str[0:9]

    # Name qualifier / variable type
    wide_df['var_type'] = wide_df['variable'].str.extract(r'\d+([A-Z]+)', expand=False)
    
    # Change description in var type
    wide_df['var_type'] = np.where(wide_df['var_type'] == 'E', 'Estimate',
                                np.where(wide_df['var_type'] == 'M', 'Estimate MOE',
                                            np.where(wide_df['var_type'] == 'PE', 'Percentage',
                                                     np.where(wide_df['var_type'] == 'PM', 'Percentage MOE', np.nan))))
    
    # PREPARE META DATA
    # Sort values
    meta_df = meta_df.sort_values(by = 'variable')
    
    # Keep only variables in groups DO02 to DP05
    meta_var_df = meta_df[meta_df['group'].isin(['DP02', 'DP03', 'DP04', 'DP05'])].copy()
    
    # Variable base name
    meta_var_df['var_name_base'] = meta_var_df['variable'].str[0:9]

    # Name qualifier / var type
    meta_var_df['var_type'] = meta_var_df['variable'].str.extract(r'\d+([A-Z]+)', expand=False)
    
    # Gen new label column without 'Estimate' or 'Percent' prefix
    meta_var_df['base_label'] = meta_var_df['label'].replace('Estimate|Percent', '', regex=True)
    
    # Keep only the columns we need
    meta_labels_df = meta_var_df[['var_name_base', 'base_label', 'group']].copy()
    
    # Drop duplicates
    meta_labels_df = meta_labels_df.drop_duplicates()
    
    # Label format: Remove initial '!!'
    meta_labels_df['base_label'] = meta_labels_df['base_label'].str.lstrip('!!')

    # Label format: Add a column for the topic of the variable (could be useful when applying filters in Excel)
    meta_labels_df['var_topic'] = meta_labels_df['base_label'].str.split('!!').str[0]

    # Label format: Replace '!!' with ' - '
    meta_labels_df['base_label'] = meta_labels_df['base_label'].str.replace('!!', ' - ', regex=True)

    
    
    # MERGE DATA WITH LABELS
    # Merge
    final_df = pd.merge(wide_df, meta_labels_df, how = 'left', left_on='var_name_base', right_on='var_name_base')
    
    # FORMAT FINAL DATA FRAME
    # Drop unnecessary columns
    final_df = final_df.drop(columns = ['var_name_base'])               # Used only for merge
    # rename columns
    final_df = final_df.rename(columns = {'base_label' : 'var_label', 'group' : 'var_group'})
    # sort columns
    final_df = final_df.sort_index(axis = 1, ascending = False)
    
    # GEO CODES
    geo_labels = data_df[['public use microdata area', 'state', 'NAME']]
    geo_labels = geo_labels.rename(columns={'public use microdata area' : 'puma_code', 'state' : 'state_code', 'NAME' : 'puma_name'} )
    
    return(final_df, geo_labels)

In [78]:
dp_wide, geocodes = acs_dp_to_wide(data_df=data_df, meta_df=meta_df, sample='1_yr', vintage=2024)

In [79]:
dp_wide

,vintage,variable,var_type,var_topic,var_label,var_group,sample,puma_4503,puma_4502,puma_4501,...,puma_4165,puma_4121,puma_4112,puma_4111,puma_4110,puma_4109,puma_4108,puma_4107,puma_4104,puma_4103
0,2024,DP03_0001E,Estimate,EMPLOYMENT STATUS,EMPLOYMENT STATUS - Population 16 years and over,DP03,1_yr,138293.0,115611.0,152902.0,...,191133.0,142503.0,155889.0,111508.0,105499.0,102122.0,193797.0,202107.0,115236.0,144345.0
1,2024,DP03_0001M,Estimate MOE,EMPLOYMENT STATUS,EMPLOYMENT STATUS - Population 16 years and over,DP03,1_yr,9496.0,7868.0,7711.0,...,12244.0,10560.0,10361.0,10100.0,10057.0,8252.0,10319.0,12109.0,9901.0,9269.0
2,2024,DP03_0001PE,Percentage,EMPLOYMENT STATUS,EMPLOYMENT STATUS - Population 16 years and over,DP03,1_yr,138293.0,115611.0,152902.0,...,191133.0,142503.0,155889.0,111508.0,105499.0,102122.0,193797.0,202107.0,115236.0,144345.0
3,2024,DP03_0001PM,Percentage MOE,EMPLOYMENT STATUS,EMPLOYMENT STATUS - Population 16 years and over,DP03,1_yr,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2024,DP03_0002E,Estimate,EMPLOYMENT STATUS,EMPLOYMENT STATUS - Population 16 years and ov...,DP03,1_yr,88797.0,68769.0,91362.0,...,143202.0,108486.0,98623.0,63372.0,69618.0,62957.0,137634.0,134341.0,88148.0,84740.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
543,2024,DP03_0136PM,Percentage MOE,PERCENTAGE OF FAMILIES AND PEOPLE WHOSE INCOME...,PERCENTAGE OF FAMILIES AND PEOPLE WHOSE INCOME...,DP03,1_yr,2.3,2.7,3.5,...,3.0,2.5,4.7,8.4,7.4,8.1,1.1,2.0,4.6,5.8
544,2024,DP03_0137E,Estimate,PERCENTAGE OF FAMILIES AND PEOPLE WHOSE INCOME...,PERCENTAGE OF FAMILIES AND PEOPLE WHOSE INCOME...,DP03,1_yr,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
545,2024,DP03_0137M,Estimate MOE,PERCENTAGE OF FAMILIES AND PEOPLE WHOSE INCOME...,PERCENTAGE OF FAMILIES AND PEOPLE WHOSE INCOME...,DP03,1_yr,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
546,2024,DP03_0137PE,Percentage,PERCENTAGE OF FAMILIES AND PEOPLE WHOSE INCOME...,PERCENTAGE OF FAMILIES AND PEOPLE WHOSE INCOME...,DP03,1_yr,19.0,28.6,32.3,...,14.8,9.3,27.8,42.6,31.1,33.8,11.3,17.9,15.5,31.7
547,2024,DP03_0137PM,Percentage MOE,PERCENTAGE OF FAMILIES AND PEOPLE WHOSE INCOME...,PERCENTAGE OF FAMILIES AND PEOPLE WHOSE INCOME...,DP03,1_yr,6.4,7.1,5.1,...,3.1,2.7,4.6,5.1,5.4,7.5,2.4,3.4,2.9,5.0

In [80]:
sample = '1_yr'
vintage = '2024'
geography = 'PUMA'
print(fr'C:\Users\HerreraMartinezR\OneDrive - NYC Office of Management and Budget\Data\ACS\{sample}_sample\{vintage}\{geography}')

C:\Users\HerreraMartinezR\OneDrive - NYC Office of Management and Budget\Data\ACS\1_yr_sample\2024\PUMA

In [81]:
# Save data

directory = r'C:\Users\HerreraMartinezR\OneDrive - NYC Office of Management and Budget\Data\ACS\1_yr_sample\2024\PUMA'
file_name = '1_yr_ACS_2024_PUMA_NYC_DP03_ECONOMIC_CHAR.xlsx'

# Ensure the folder exists (create if missing)
os.makedirs(directory, exist_ok=True)


full_path = os.path.join(directory, file_name)

with pd.ExcelWriter(full_path) as writer:
    dp_wide.to_excel(writer, sheet_name = 'data', index = False)
    geocodes.to_excel(writer, sheet_name = 'geo_labels', index = False)